language: c
sudo: required

addons:
   apt:
      packages:
         - cmake

env:
   matrix:
      BUILD_SCRIPT="mkdir cmake-build &&
      cd cmake-build &&
      cmake .. &&
      make"
      CODE_COVERAGE="no"
      DEPLOY_DOCUMENTATION="no"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -y gfortran libblas-dev liblapack-dev;
      sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/$(gfortran -dumpversion | cut -f1,2 -d.)/libgfortran.so /usr/local/lib;
    else
      brew install gcc;
    fi
    
install:
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

script:
   - mkdir cmake-build
   - cd cmake-build
   - cmake ..
   - make
   - ls
   - ls *
   - cd ../
   - cmake-build/mc/mc > output.new
   - diff output.new tests/output.ref
