FUNCTION CALENG(COORDS,NATOMS)
IMPLICIT DOUBLE PRECISION(A-Z)
INTEGER :: NATOMS
DOUBLE PRECISION :: COORDS(NATOMS,3)
DOUBLE PRECISION :: K, EPS, SIGMA
COMMON /ENERGY/ K, EPS, SIGMA
EPS = 10.2 ! K
SIGMA = 2.28 ! ANGSTROM
K = 0.0019872041 ! KCAL/(MOL*K)
CALENG = 0.0
! LOOP OVER ALL PAIRS
DO 10 I=1, NATOMS
DO 1234 J=I+1, NATOMS
DR = ( COORDS(I,1) - COORDS(J,1) ) ** 2 + ( COORDS(I,2) - COORDS(J,2) ) ** 2 + ( COORDS(I,3) - COORDS(J,3) ) ** 2
DR = DR**(0.5)
S6 = ( SIGMA / DR )**6
CALENG = CALENG + 4.0*EPS*K*( S6**2 - S6 )
1234 CONTINUE
10 CONTINUE
END FUNCTION CALENG
